on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  mine-alpine-purls:
    runs-on: ubuntu-24.04
    name: Mine alpine Package-URLs
    steps:
    - uses: aboutcode-org/scancode-action@purl-mining-branch
      with:
        scancodeio-repo-branch: "minecode-git-deployment"
        scancodeio-extras: "mining"
        pipelines: "mine_alpine"
      env:
        FEDERATEDCODE_GIT_ACCOUNT_URL: https://github.com/aboutcode-data
        FEDERATEDCODE_GIT_SERVICE_TOKEN: ${{ secrets.MINING_GITHUB_TOKEN }}
        FEDERATEDCODE_GIT_SERVICE_NAME: "AboutCode Automation"
        FEDERATEDCODE_GIT_SERVICE_EMAIL: "automation@aboutcode.org"
